[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0", "wheel>=0.37.1"]


[project]
name = "Battle Bots"
version = "0.0.1"
requires-python = ">=3.10"
authors = {name = "Ryan Freund"}
